apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
  namespace: inventory-app
type: Opaque

stringData:
  SA_PASSWORD: "YourStrong@Passw0rd123"
  ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=InventoryDb;User Id=sa;Password=YourStrong@Passw0rd123;TrustServerCertificate=True"
